version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u232-jdk
    steps:
      - checkout
      - run: 
          name: "Build the *.cap files"
          command: [ -f build.sh ] && ./build.sh
