version: 2

jobs:
  build:
    docker:
      - image: mingc/android-build-box
    steps:
      - checkout
      - run: git submodule update --init
      - run:
          name: "Build the *.cap files"
          command: |
              if test -f "build.sh"; then
                  ./build.sh
              fi
